export enum modeType {
  imaggaScale = "imaggaScale",
  imaggaCrop = "imaggaCrop",
  crop = "crop",
  fill = "fill",
  scale = "scale",
  minimumPad = "minimumPad",
  fit = "fit",
  pad = "pad",
  limitFit = "limitFit",
  thumbnail = "thumbnail",
  limitFill = "limitFill",
  minimumFit = "minimumFit",
  limitPad = "limitPad",
  fillPad = "fillPad",
}
